<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>s4piControls</AssemblyName>
    <RootNamespace>s4piControls</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\s4pi\Interfaces\Interfaces.csproj" />
    <ProjectReference Include="..\..\CS System Classes\CS System Classes.csproj" />
    <ProjectReference Include="..\Extensions\Extensions.csproj" />
    <ProjectReference Include="..\CustomForms\CustomForms.csproj" />
  </ItemGroup>

</Project>
