<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Package</AssemblyName>
    <RootNamespace>Package</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Interfaces\Interfaces.csproj" />
    <ProjectReference Include="..\..\CS System Classes\CS System Classes.csproj" />
  </ItemGroup>

</Project>
