<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>ImageResource</AssemblyName>
    <RootNamespace>ImageResource</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\s4pi\Interfaces\Interfaces.csproj" />
  </ItemGroup>

</Project>
