<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>JazzResource</AssemblyName>
    <RootNamespace>JazzResource</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\s4pi\Interfaces\Interfaces.csproj" />
    <ProjectReference Include="..\GenericRCOLResource\GenericRCOLResource.csproj" />
  </ItemGroup>

</Project>
