<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Interfaces</AssemblyName>
    <RootNamespace>Interfaces</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CS System Classes\CS System Classes.csproj" />
    <ProjectReference Include="..\Settings\Settings.csproj" />
  </ItemGroup>

</Project>
