<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>CS System Classes</AssemblyName>
    <RootNamespace>CSSystemClasses</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.7" />
  </ItemGroup>

</Project>
