<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>s4pi.Resource.Commons</AssemblyName>
    <RootNamespace>s4piResourceCommons</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\s4pi\Interfaces\Interfaces.csproj" />
    <ProjectReference Include="..\CS System Classes\CS System Classes.csproj" />
    <ProjectReference Include="..\s4pi Extras\Extensions\Extensions.csproj" />
  </ItemGroup>

</Project>
