<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>CatalogResource</AssemblyName>
    <RootNamespace>CatalogResource</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\s4pi\Interfaces\Interfaces.csproj" />
    <ProjectReference Include="..\..\s4pi.Resource.Commons\s4pi.Resource.Commons.csproj" />
  </ItemGroup>

</Project>
