<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Sims4Tools.Platform.CrossPlatform</AssemblyName>
    <RootNamespace>Sims4Tools.Platform.CrossPlatform</RootNamespace>
    <Description>Cross-platform services for Sims4Tools</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sims4Tools.Platform.Abstractions\Sims4Tools.Platform.Abstractions.csproj" />
  </ItemGroup>

</Project>
