<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>s4pe</AssemblyName>
    <RootNamespace>s4pe</RootNamespace>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CS System Classes\CS System Classes.csproj" />
    <ProjectReference Include="..\s4pi\Interfaces\Interfaces.csproj" />
    <ProjectReference Include="..\s4pi\Package\Package.csproj" />
    <ProjectReference Include="..\s4pi\WrapperDealer\WrapperDealer.csproj" />
    <ProjectReference Include="..\s4pi Extras\CustomForms\CustomForms.csproj" />
    <ProjectReference Include="..\s4pi Extras\Extensions\Extensions.csproj" />
    <ProjectReference Include="..\s4pi Extras\Helpers\Helpers.csproj" />
    <ProjectReference Include="..\s4pi Wrappers\ImageResource\ImageResource.csproj" />
    <ProjectReference Include="..\s4pi.Resource.Commons\s4pi.Resource.Commons.csproj" />
    <ProjectReference Include="..\s4pi Extras\DDSPanel\DDSPanel.csproj" />
    <ProjectReference Include="..\s4pi Extras\s4piControls\s4piControls.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

</Project>
