<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>CustomForms</AssemblyName>
    <RootNamespace>CustomForms</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CS System Classes\CS System Classes.csproj" />
  </ItemGroup>

</Project>
